/*
 * Copyright (C) BRIGUET Systems, Inc - All Rights Reserved
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 * Written by LAMACHE, Juin 2018
 */
package org.ihm;



import java.util.List;
import org.ihm.components.GamerComponent;
import org.ihm.components.IGamerComponent;
import org.metier.salon.Gamer;



/**
 * Crée une fenêtre de choix de joueur à qui demander une carte
 * @author Joseph BRIGUET
 * @author Ben YOUSSOUFA
 * @author Fabien Tressaille
 * @author Damien ARROUDJ
 */
public class ChoiceGamer extends javax.swing.JDialog implements IGamerComponent{

    
    /**
     * Correspond aux joueurs possibles
     */
    List<Gamer> gamers;
    /**
     * Correspond au joueur sélectionné
     */
    Gamer selected;
    
    
    
    /**
     * Crée la fenêtre
     * @param parent Correspond à la fenêtre parente
     * @param modal Si oui ou non on veut que cette fenêtre soit modale
     * @param gamers Correspond à la liste des joueurs
     */
    public ChoiceGamer(java.awt.Frame parent, boolean modal, List<Gamer> gamers) {
        super(parent, modal);
        initComponents();
        this.gamers = gamers;
        
        for(int i=0;i<gamers.size();i++){
            GamerComponent gc = new GamerComponent();
            gc.setGamer(gamers.get(i));
            gc.addIGamerComponent(this);
            jPanel1.add(gc);
            jPanel1.repaint();
        }
    }
    
    
    
    /**
     * Affiche la fenêtre et renvoie le joueur sélectionné
     * @return 
     */
    public Gamer showForm(){
        super.setVisible(true);
        return selected;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(368, 148));
        setMinimumSize(new java.awt.Dimension(368, 148));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(368, 148));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 10, 0));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void gamerMouseClicked(GamerComponent gc) {
        selected = gc.getGamer();
        this.dispose();
    }
}